default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: recruitd_user

development:
  <<: *default
  database: raymond_photo_dev

test:
  <<: *default
  database: raymond_photo_test
